### PR TITLE
Fix race tooltip

### PR DESCRIPTION
**Pull request by cfhull**
closes https://github.com/Hyperobjekt/seeing-solitary/issues/179

### CODE REVIEW

**Comment by james-minton** [comment]
Also a thought: "in solitary" is the thing we're concerned about; feels odd, then, that "total custodial" gets the big bright primary blue and "in solitary" is grey. Can we swap those colors in both the chart and legend?

**Comment by cfhull** [comment]
@james-minton Done!

**Comment by james-minton** [comment]
@cfhull this is good but with fresh eyes, I'm seeing a new wrinkle. It's confusing to me that in the tooltip we're reporting "in solitary" first, followed by total custodial, but reading left to right in the graph, it goes total custodial, then in solitary.

Screen Shot 2023-01-10 at 5 56 00 PM

I think the order in the tooltip is good, and we should switch the order of the bars as well as the legend (on federal and state pages. 

Then I think we'll be good to merge!

**Comment by cfhull** [comment]
@james-minton Give that another test. Think it's good now.

**Pull request merged**
