### PR TITLE
Hexbin tooltip

### PR DESCRIPTION
**Pull request by cfhull**
https://github.com/Hyperobjekt/seeing-solitary/issues/128

### CODE REVIEW

**Comment by james-minton** [comment]
Thanks for this, looking great so far -- I know it's just a draft and you're probably aware of all these issues but in case it's helpful:

- seeing NaN% where percentages should be zero
Screen Shot 2022-10-31 at 11 10 03 PM

- wherever you have an absolute figure >0 but where the percentage is <1, we want it so we never show a 0% -- it should be "<1%" here and other "bright yellow" places


Screen Shot 2022-10-31 at 11 14 01 PM

- tooltip currently stays active when moused out, should disappear instead

Again, sorry if I'm being annoying and you're aware already, just making sure!

**Comment by cfhull** [comment]
> Thanks for this, looking great so far -- I know it's just a draft and you're probably aware of all these issues but in case it's helpful:
> 
> * seeing NaN% where percentages should be zero
> 
> Screen Shot 2022-10-31 at 11 10 03 PM
> 
> * wherever you have an absolute figure >0 but where the percentage is <1, we want it so we never show a 0% -- it should be "<1%" here and other "bright yellow" places
> 
> Screen Shot 2022-10-31 at 11 14 01 PM
> 
> * tooltip currently stays active when moused out, should disappear instead
> 
> Again, sorry if I'm being annoying and you're aware already, just making sure!

I left a comment about that on the ticket. https://github.com/Hyperobjekt/seeing-solitary/issues/128#issuecomment-1296408997

I'll have to look at the data again to see what the exact problem was, but I think the problem was that the hexbin data, and the charts data were coming from separate files, and they didn't seem to match (custodial was missing on some, had a different number, etc). I wanted to verify what data we wanted to show before digging in too deep though. If that's what the tooltip data should be, then I will take another look at the underlying data, and see what the issue is.

**Comment by james-minton** [comment]
@cfhull thanks for flagging, I am seeing the data discrepancies between this and the bar chart. FWIW the hexbin should always have data for "most recent reporting year," meaning it's going to be a mix of 2021, 2019, etc. based on when a place last responded to surveys. But it doesn't account for some of these discrepancies. I'm going to take a look.

But FYI what the tooltip is aiming to show is correct -- 

- Jurisdiction name
- the percent and number of people in solitary
- the number for the total custodial population

Just like the bar chart for "how long" below.

**Comment by cfhull** [comment]
Ok. I'll leave the data updates to you, and I'll clean up the UI.

**Comment by cfhull** [comment]
@james-minton 

This should be good to go now. I added null checks for basically everything in the tooltip, so it will show something reasonable if any data is missing. I also updated all of the tooltips to be consistent with their font sizing and styles, so please do a once-over on all the tooltips to make sure you agree with my fixes.

**Comment by james-minton** [comment]
Hey @cfhull thank you -- I'm seeing some errors locally and [failed builds on Netlify](https://app.netlify.com/sites/seeingsolitary/deploys/6361c3be4af55e0009ea6186). Maybe some conflicts, needs to be updated from `development`?

Not super urgent though, I think we'll be okay if this doesn't make it in before the event; all the better if it does though of course :-)

**Comment by cfhull** [comment]
What errors do you see? I'm not seeing any.

**Comment by james-minton** [comment]
@cfhull not sure, maybe just issues for me locally. FYI we have bigger problems now--see channel :-/

**Comment by lizlove** [comment]
@cfhull I handled the merge fixes and put Aaron's <1% work in here.

**Pull request merged**
